// Generated by scripts/sign-ar.mjs — public keys trusted to sign AR registrations.
export const TRUSTED_KEYS = {
  "omni-ar-2026-09-27": {
    "kty": "EC",
    "crv": "P-256",
    "x": "kevOLhqnSAzNHiJVviUNrj0MeKijazdjipVwqI3V8wk",
    "y": "CqdyXM5kEkUw8V6VqhyXsYW3mhcNrR8KdGfBumFqCZw",
    "ext": true
  }
};
