// Signs ar/ar-element.json into ar/ar-register.json (bundled into the app).
//
//   npm run sign:ar            sign with .keys/ar-signing-key.json (created if missing)
//   npm run sign:ar -- --days 180
//
// The private key stays in .keys/ (git-ignored). The public key is written to
// shared/security/trustedKeys.js, which the app trusts.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { signRegistration, verifyRegistration } from '../shared/security/arVerify.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const keyPath = join(root, '.keys', 'ar-signing-key.json');
const daysArg = process.argv.indexOf('--days');
const days = daysArg > 0 ? Number(process.argv[daysArg + 1]) : 365;

async function loadOrCreateKey() {
  if (existsSync(keyPath)) return JSON.parse(await readFile(keyPath, 'utf8'));
  const pair = await crypto.subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-256' }, true, ['sign', 'verify']);
  const privateJwk = await crypto.subtle.exportKey('jwk', pair.privateKey);
  const publicJwk = await crypto.subtle.exportKey('jwk', pair.publicKey);
  const keyId = `omni-ar-${new Date().toISOString().slice(0, 10)}`;
  const record = { keyId, privateJwk, publicJwk };
  await mkdir(dirname(keyPath), { recursive: true });
  await writeFile(keyPath, JSON.stringify(record, null, 2));
  console.log(`created signing key ${keyId} at ${keyPath}`);
  return record;
}

const { keyId, privateJwk, publicJwk } = await loadOrCreateKey();
const element = JSON.parse(await readFile(join(root, 'ar', 'ar-element.json'), 'utf8'));
const issuedAt = new Date();
const expiresAt = new Date(issuedAt.getTime() + days * 86_400_000);

const reg = await signRegistration(
  { keyId, issuedAt: issuedAt.toISOString(), expiresAt: expiresAt.toISOString(), element },
  privateJwk,
);

const { kty, crv, x, y } = publicJwk;
const trusted = { [keyId]: { kty, crv, x, y, ext: true } };
const check = await verifyRegistration(reg, trusted);
if (!check.ok) throw new Error(`self-check failed: ${check.reason}`);

await writeFile(join(root, 'ar', 'ar-register.json'), JSON.stringify(reg, null, 2) + '\n');
await writeFile(
  join(root, 'shared', 'security', 'trustedKeys.js'),
  `// Generated by scripts/sign-ar.mjs — public keys trusted to sign AR registrations.\n` +
    `export const TRUSTED_KEYS = ${JSON.stringify(trusted, null, 2)};\n`,
);
console.log(`signed ${element.id}@${element.version} with ${keyId}, valid until ${expiresAt.toISOString()}`);
